"""initial schema with assignments features

Revision ID: 104310093ba3
Revises: 9db6ae506419
Create Date: 2025-09-22 08:43:27.487222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104310093ba3'
down_revision = '9db6ae506419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
