"""Add semester field to User

Revision ID: ef3de76ac8f7
Revises: c58440a6fb8f
Create Date: 2025-09-18 14:24:15.245687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3de76ac8f7'
down_revision = 'c58440a6fb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('semester', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'semester')
    # ### end Alembic commands ###
