name: AI Auto-Fix & Feature Requests

on:
  workflow_dispatch:   # Run manually
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ai-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run AI Fixer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python ai_fixer.py

      - name: Apply AI Patch
        if: success()
        run: |
          if [ -f ai_patch.diff ]; then
            git apply ai_patch.diff || echo "⚠️ Patch failed, manual review required"
          else
            echo "No patch generated"
          fi

      - name: Commit & Push changes
        if: success()
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --global user.name "AI Bot"
            git config --global user.email "aibot@example.com"
            git add .
            git commit -m "🤖 AI Fixes & Feature Updates"
            git push
          fi
