name: Test OpenAI Key Secret

on:
  workflow_dispatch: {}   # allows you to trigger it manually

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment check
        run: echo "Starting test..."

      - name: Check if OPENAI_API_KEY is set
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OPENAI_API_KEY is NOT set!"
            exit 1
          else
            echo "✅ OPENAI_API_KEY is set (hidden for security)."
          fi
